### ISSUE TITLE
Clarification what is meant by Controlled Document

### ISSUE THREAD

**Issue by henkvancann** [trustoverip/egf-vlei-review#1]
### Section Name

Controlled Documents

### Line number

21

### Question/Comment

Maybe it's good to clarify what is meant by the term "Controlled Document". 

These are 'Documents for the vLEI Issuer Qualification Program'. But what does 'controlled' exactly mean, controlled by whom? Are there other important documents that are not 'controlled' and what makes the difference.

**Comment by m00sey** [comment]
@henkvancann Controlled Documents are part of the ToIP Governance Framework Metamodel and defined by the ToIP Governance working group.

**Comment by henkvancann** [comment]
Ah, OK, I missed the basics of the ToIP Gov Framework :-)). Rookie galore
