### ISSUE TITLE
No attribution to any of the TOIP and/or SOVRIN governance frameworks?

### ISSUE THREAD

**Issue by mwherman2000** [trustoverip/egf-vlei-review#10]
### Section Name

All documents?

### Line number

1

### Question/Comment

Based on a quick scan I don't see any attribution to either the TOIP or SOVRIN governance frameworks.

Do all of the GLIEF documents in this repository represent completely original work products?

NOTE:  Of the 2 foundational frameworks, SOVRIN has the most restrictive licensing requirements.

**Comment by kmckenna-gleif** [comment]
Thank you for your review of the vLEI EGF.  
The vLEI EGF uses the ToIP Governance Framework Metamodel.
I understand that in the new Companion Guide recently completed in the ToIP GSWG, it recommended to state that an EGF uses the ToIP Governance Framework Metamodel.  This statement will be added in Primary Document.
