### ISSUE TITLE
Appendix 5 appears to be missing?

### ISSUE THREAD

**Issue by mwherman2000** [trustoverip/egf-vlei-review#7]
### Section Name

Appendix 5

### Line number

1

### Question/Comment

Appendix 5 appears to be missing from the appendices/ folder

**Comment by kmckenna-gleif** [comment]
Please see the following explanation in the Background document which also is noted in the Primary Document and the vLEI Services Catalog documents: 
'_Appendix 5: Qualified vLEI Issuer Service Level Agreement (SLA)_
 A document that details the services to be provided by GLEIF and the Qualified vLEI Issuers
 and the service level requirements for these services.
 The formal SLA will be prepared prior to the implementation of the vLEI Issuer Qualification
 Program in 2022 as Appendix 5 to the vLEI Issuer Qualification Agreement.

 In the meantime, a vLEI Services Catalog has been prepared to provide background of the
 services that will be developed for GLEIF and for the network of Qualified vLEI Issuers.
