### ISSUE TITLE
No copyright statement on most (all?) documents

### ISSUE THREAD

**Issue by mwherman2000** [trustoverip/egf-vlei-review#8]
### Section Name

All documents

### Line number

1

### Question/Comment

None of the documents appear to have a copyright statement. This is problematic given TOIP's charter.  Is it section 6? This entire project may need to be removed.

**Comment by kmckenna-gleif** [comment]
GLEIF will publish the vLEI Ecosystem Governance Framework on the GLEIF website.  All documents published on the GLEIF website are published under the Creative Commons Attribution license.  This is noted in a general statement on the GLEIF website and is not noted individually on each document published on the GLEIF website.
