### ISSUE TITLE
No LICENSE agreement attached to this repository

### ISSUE THREAD

**Issue by mwherman2000** [trustoverip/egf-vlei-review#9]
### Section Name

All documents

### Line number

1

### Question/Comment

There is no LICENSE agreement attached to this repository. This problematic given this is a TOIP repository.

**Comment by kmckenna-gleif** [comment]
GLEIF will publish the vLEI Ecosystem Governance Framework on the GLEIF website.  All documents published on the GLEIF website are published under the Creative Commons Attribution license.  This is noted in a general statement on the GLEIF website and is not noted individually on each document published on the GLEIF website.
